apiVersion: apps/v1
kind: Deployment
metadata:
  name: capivara-deployment
spec:
  replicas: 2
  template:
    metadata:
      name: capivara-app
      labels: 
        app: capivara-app
    spec:
      containers:
        - name: capivara-app
          image: damirojr/capivara:1.0
          ports: 
           - containerPort: 80
  selector:
    matchLabels:
      app: capivara-app
