apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: capivara-ingress
spec:
  rules:
  - host: localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: capivara-service
            port:
              number: 80
